folio-org/ui-remote-storage

- CHANGELOG.md
- package.json
- translations/ui-remote-storage/en.json
https://issues.folio.org/browse/UIRS-3 …
> UIRS-3 Permission: Remote storage configuration

- translations/ui-remote-storage/ar.json
- translations/ui-remote-storage/es.json
- translations/ui-remote-storage/es_419.json
- translations/ui-remote-storage/es_ES.json
- translations/ui-remote-storage/ja.json
Please do not manually merge this pull request.  It will either be automatically merged or withdrawn.
> Update translation strings as of 20201102T140138

- translations/ui-remote-storage/fr_FR.json
- translations/ui-remote-storage/pt_BR.json
Please do not manually merge this pull request.  It will either be automatically merged or withdrawn.
> Update translation strings as of 20201105T151643

- translations/ui-remote-storage/ber.json
Please do not manually merge this pull request.  It will either be automatically merged or withdrawn.
> Update translation strings as of 20201109T135508

- translations/ui-remote-storage/pt_BR.json
Please do not manually merge this pull request.  It will either be automatically merged or withdrawn.
> Update translation strings as of 20201110T192302

- src/const.js
Update time units list 
While it's helpful for reviewers to help identify potential …
> Change time units

- src/CreateRemoteStorage/CreateRemoteStorageContainer.js
- src/RemoteStorageEditor/RemoteStorageEditorContainer.js
- src/RemoteStorageForm/RemoteStorageForm.js
Remove status URL on changing provider …
> Fix provider change

- .eslintrc
- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIRS-13
https://issues.folio.org/browse/UIRS-19
While it's …
> UIRS-13 Update stripes to v6.0.0, stripes-cli to v2

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIRS-10 …
> UIRS-10 Add personal data disclosure form

- package.json
https://issues.folio.org/browse/UIRS-22 …
> UIRS-22 Update permissions

- src/const.js
- translations/ui-remote-storage/en.json
https://issues.folio.org/browse/UIRS-15 …
> UIRS-15 Change Caiasoft id

- src/CreateRemoteStorage/CreateRemoteStorageContainer.js
- src/RemoteStorageEditor/RemoteStorageEditorContainer.js
- src/RemoteStorageForm/RemoteStorageForm.js
> UIRS-15 refactor form: use values from props

- src/Details/CaiaSoft/AccessionWorkflow.js
- src/Editor/Editor.test.js
- src/Editor/TheForm.js
- translations/ui-remote-storage/en.json
> UIRS-23 add tool-tip, fix options, add test

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIRS-27 …
> UIRS-27 Add "remote-storage.providers.collection.get" sub-permission

- src/Details/Sections/General/Providers.js
- src/Details/Sections/General/index.js
- src/Details/Sections/General/useProvidersOptions.js
- src/Editor/Editor.test.js
- src/Editor/TheForm.js
- src/RemoteStorageDetails/RemoteStorageDetailsContainer.js
- src/RemoteStorageDetails/RemoteStorageDetailsContainer.test.js
- translations/ui-remote-storage/en.json
- add loading state and placeholder for Providers
- add validation for Name and Providers
- fix Remove modal: change "Save" button for "Delete"
- improve form layout
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIRS-23 Form improvements

- CHANGELOG.md
- package.json
UIRS-27 Add to "Remote storage: Create, read, update, delete" all the missing permissions on configurations
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UIRS-27 Add missing permissions on configurations

- CHANGELOG.md
- src/Details/CaiaSoft/ReturningWorkflow.js
- src/Details/CaiaSoft/Sections.js
- src/Details/Sections/General/Providers.js
- src/Editor/Editor.test.js
- translations/ui-remote-storage/en.json
https://issues.folio.org/browse/UIRS-24 …
> UIRS-24 Add Returning workflow preference

- package.json
> UIRS-27 Add remote-storage-providers to okapiInterfaces

- CHANGELOG.md
- Jenkinsfile
- package.json
https://issues.folio.org/browse/UIRS-30 …
> UIRS-30 Compile Translation Files into AST Format

- translations/ui-remote-storage/en.json
Follow-up for https://issues.folio.org/browse/UIRS-32
While it's helpful for reviewers to …
> UIRS-32 Remove leftover translations for "Accession workflow preference"

- CHANGELOG.md
- src/Details/CaiaSoft/AccessionWorkflow.js
- src/Details/CaiaSoft/Sections.js
- src/Editor/Editor.test.js
- translations/ui-remote-storage/en.json
https://issues.folio.org/browse/UIRS-41 …
> UIRS-41 Add Accession holdings workflow preference

- package.json
https://issues.folio.org/browse/UIRS-42 …
> UIRS-42 Update "remote-storage-mappings" interface

- src/AccessionTables/ConfigurationsSelect.js
- src/AccessionTables/Content.js
> UIRS-48 Add dropdown to select CaiaSoft configuration

- src/API/useOkapiQuery.js
- src/AccessionTables/AccessionTables.js
- src/AccessionTables/ConfigurationsSelect.js
- src/AccessionTables/Content.js
- src/AccessionTables/Table.js
- src/AccessionTables/useCaiaSoftConfigurations.js
https://issues.folio.org/browse/UIRS-48 …
> UIRS-48 Refactor

- .eslintrc
- src/Configurations/Configurations.js
- src/Configurations/DetailsPane/DetailsPane.js
- src/Configurations/DetailsPane/Menu.js
- src/const.js
- translations/ui-remote-storage/en.json
https://issues.folio.org/browse/UIRS-49 …
> UIRS-49 Add menu item to Configuration Action menu

- src/AccessionTables/AccessionTables.test.js
> UIRS-55 Add tests

- package.json
- src/API/AccessionTable.js
- src/API/Locations.js
- src/API/index.js
- src/API/useOkapiMutation.js
- src/AccessionTables/Table.js
- src/AccessionTables/components/Location.js
- src/AccessionTables/components/LocationSelection/LocationSelection.js
- src/AccessionTables/components/LocationSelection/index.js
- src/AccessionTables/components/index.js
- src/AccessionTables/useCaiaSoftConfigurations.js
- src/Configurations/ListPane/Menu.js
- src/data/AccessionTable.js
- src/data/Locations.js
- src/data/index.js
https://issues.folio.org/browse/UIRS-50 …
> UIRS-50 Add theTable

- src/API/AccessionTable.js
https://issues.folio.org/browse/UIRS-50 …
> UIRS-50 Temporal fix Table refresh after mutation

- package.json
- src/AccessionTables/AccessionTables.test.js
https://issues.folio.org/browse/UIRS-55 …
> UIRS-55 Wrap test with redux provider

- package.json
> UIRS-39 Update back-end dependencies

- CHANGELOG.md
- src/Configurations/DetailsPane/Menu.js
https://issues.folio.org/browse/UIRS-39
On comment https://issues.folio.org/browse/UIRS-39?focusedCommentId=105909&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-105909
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> UIRS-39 Add table icon in Actions menu

- package.json
https://issues.folio.org/browse/UIRS-51 …
> UIRS-51 Refine permission sets, add `locations` okapi interface

- CHANGELOG.md
- src/Configurations/EditorLayer/Editor.test.js
https://issues.folio.org/browse/UIRS-34 …
> UIRS-34 Fix test

- CHANGELOG.md
- src/AccessionTables/test/Table.test.js
- src/Configurations/EditorLayer/Editor.js
- src/Configurations/EditorLayer/Editor.test.js
- src/Configurations/EditorLayer/prepareValuesForAPI.js
- src/Configurations/EditorLayer/prepareValuesForAPI.test.js
- src/Configurations/Fields/Fields.js
- src/Configurations/Fields/Sections/General/index.js
- src/Configurations/Fields/Sections/Syncronization.test.js
- translations/ui-remote-storage/en.json
This section should be present only for Dematic StagingDirector.
The corresponding parameter `accessionDelay` is `undefined` for any other provider.
https://issues.folio.org/browse/UIRS-62
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> UIRS-62 "Data synchronization schedule" additional requirements

- src/Configurations/EditorLayer/prepareValuesForAPI.js
- src/Configurations/EditorLayer/prepareValuesForAPI.test.js
BE doesn't break without it anymore )
https://issues.folio.org/browse/UIRS-62
While it's …
> UIRS-62 Remove excessive accessionTimeUnit

- src/API/Configurations.js
- src/AccessionTables/useCaiaSoftConfigurations.js
- src/Configurations/Delete/useScenario.js
- src/Configurations/DetailsPane/DetailsPane.js
- src/Configurations/EditorLayer/Editor.js
- src/Configurations/EditorLayer/EditorLayer.js
- src/Configurations/ListPane/List.js
- src/data/Configurations/index.js
- src/data/Configurations/mutations.js
- src/data/Configurations/prepareMutationValues.js
- src/data/Configurations/prepareMutationValues.test.js
- src/data/Configurations/queries.js
- src/data/index.js
Refactor Configurations API: separate data-specific aspects into `data` layer
- sorting
- preparing values for mutations
follow-up for https://issues.folio.org/browse/UIRS-62
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIRS-62 Refactor Configurations API: separate data-specific aspects

- CHANGELOG.md
- src/data/Configurations/queries.js
https://issues.folio.org/browse/UIRS-59 …
> UIRS-59 Unify configurations sorting order over the module

- CHANGELOG.md
- src/Configurations/Configurations.js
https://issues.folio.org/browse/UIRS-56
The "Remote storage" page unavailable after creating a configuration with an existing name
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> UIRS-56 Fix navigation on Configuration editor close

- src/AccessionTables/components/LocationSelection/LocationSelection.js
https://issues.folio.org/browse/UIRS-60 …
> UIRS-60 Make search in Locations Select highlight the search criterion in results

- CHANGELOG.md
- package.json
- src/AccessionTables/Table.js
- src/AccessionTables/test/setup.js
- src/Configurations/Configurations.js
- src/Configurations/EditorLayer/EditorLayer.js
- src/components/ActionMenu/Item.js
https://issues.folio.org/browse/UIRS-63 …
> Release 2.0.1

- CHANGELOG.md
- src/API/Providers.js
- src/API/index.js
- src/Configurations/Fields/Sections/General/useProvidersOptions.js
- src/Configurations/ListPane/List.js
- src/data/Configurations/queries.js
- src/data/Providers.js
- src/data/index.js
- translations/ui-remote-storage/en.json
https://issues.folio.org/browse/UIRS-53 …
> UIRS-53 Refactor providers-related code

- CHANGELOG.md
- src/data/Locations.js
https://issues.folio.org/browse/UIRS-82 …
> UIRS-82 Created locations not displaying in accession table

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIRS-88 …
> UIRS-88 move @babel/eslint-parser to devDependencies

- CHANGELOG.md
- src/Configurations/ListPane/ListPane.js
4th pane appearing when nothing is selected in 3rd
Issue: https://issues.folio.org/browse/UIRS-90
Settings the Default width of the third pane as 'fill'
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> UIRS-90 - update default width of ListPane

- CHANGELOG.md
- package.json
bump stripes to 8.0.0 for Orchid/2023-R1
Issue: https://issues.folio.org/browse/UIRS-94 …
> UIRS-94 - bump stripes to 8.0.0 for Orchid/2023-R1

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
[UIRS-103](https://issues.folio.org/browse/UIRS-103) - Update Node.js to v18 in GitHub Actions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIRS-103 - Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIRS-108
While it's helpful for reviewers to help …
> Release v5.1.0 - Quesnelia Release

- CHANGELOG.md
- src/API/test/setup.js
- src/AccessionTables/AccessionTables.js
- src/AccessionTables/test/Responses.test.js
- src/AccessionTables/test/setup.js
- src/Configurations/Configurations.js
- src/Configurations/DetailsPane/DetailsPane.js
- src/Configurations/test/Configurations.test.js
- src/Configurations/test/Responses.test.js
- src/RemoteStorageSettings.js
- src/RemoteStorageSettings.test.js
- translations/ui-remote-storage/en.json
[UIRS-110](https://folio-org.atlassian.net/browse/UIRS-110) - Add Html title for Remote Storage Settings Pages.
Implemented all Users Settings Page title using [TitleManager](https://github.com/folio-org/stripes-core/blob/master/src/components/TitleManager/TitleManager.js) Component from stripes-core.
Ideally all of the PRs involved in breaking changes …
> UIRS-110 - Add Html title for Remote Storage Settings Pages

- CHANGELOG.md
- package.json
- src/API/test/Configurations/useSingleQuery.test.js
[UIRS-107](https://folio-org.atlassian.net/browse/UIRS-107) - directly satisfy ky dependency
Move "ky" dependency to direct dependency
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIRS-107 - directly satisfy ky dependency

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/AccessionTables/test/ConfigurationSelect.test.js
[UIRS-118](https://folio-org.atlassian.net/browse/UIRS-118) - Upgrade version for actions/upload-artifact from v2 to v4.
[UIRS-117](https://folio-org.atlassian.net/browse/UIRS-117) - Bump "@folio/stripes-acq-components" version to v6.0.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> UIRS-118 - Upgrade version for `actions/upload-artifact` from v2 to v4.

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIRS-123; https://folio-org.atlassian.net/browse/UIRS-122
> UIRS-123, UIRS-122: migrate stripes-* deps; react-intl to v7

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIRS-126
> UIRS-126: Bump @folio/stripes-acq-components to 7.0.0
